// Generated by CoffeeScript 1.6.3
var app, express, util;

util = require('util');

express = require('express.io');

app = express();

app.http().io();

app.io.route('ready', function(req) {
  var channel, msg;
  channel = req.data.channel;
  msg = req.data.msg;
  req.io.join(channel);
  return app.io.room(channel).broadcast('announce', {
    message: msg
  });
});

util.log('server start');

app.listen(7076);
